version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test: 
    docker: 
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm testing"
      - run: npm install
      - run: npm test
  random: 
    docker: 
      - image: circleci/node:8.9
      checkout
      - run: echo "Hellloo"
workflows:
  version: 2
  build_test_random:
    jobs: 
     - build
     - random
     - test:
      requires: 
      - random